# Generated by Django 3.1 on 2020-08-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
