# Generated by Django 3.1 on 2020-08-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200807_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='number_of_reviews',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='count',
        ),
        migrations.AddField(
            model_name='movie',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
